server:
  port: 8081
  servlet:
    context-path: /video-service

spring:
  application:
    name: video-service
  config:
    import: optional:config/application-secret.yml

youtube:
  api:
    base-url: https://www.googleapis.com/youtube/v3
    key: ${youtube.api.key}
    default-max-results: 10

management:
  endpoints:
    web:
      exposure:
        include: health, info